### PR TITLE
Create Oyebamiji Benjamin (Web Tech)

### PR DESCRIPTION
**Pull request by ghost**
220502076
Computer science

### CODE REVIEW

**Comment by ghost** [comment]
[WEB TECH.zip](https://github.com/Tywahladeh/CSC-211StudentPortfolio/files/14370872/WEB.TECH.zip)

**Comment by Eltimios** [comment]
You were told to upload files not Zip file

**Comment by Lobbylings** [comment]
> You were told to upload files not Zip file

Lol

**Comment by Eltimios** [comment]
> > You were told to upload files not Zip file
> 
> Lol

no mind am, lol

**Pull request closed without merging**
